version: "3.8"

services:
  nest2d-worker-dev:
    image: ghcr.io/vovastelmashchuk/dxf-nesting-processor:${GIT_COMMIT_SHA:-latest}
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SECRET_FILE=/run/secrets/nest2d-secret-dev
    secrets:
      - nest2d-secret-dev
    deploy:
      update_config:
        order: start-first

  nest2d-worker-prod:
    image: ghcr.io/vovastelmashchuk/dxf-nesting-processor:${GIT_COMMIT_SHA:-latest}
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - SECRET_FILE=/run/secrets/nest2d-secret
    secrets:
      - nest2d-secret
    deploy:
      update_config:
        order: start-first

secrets:
  nest2d-secret-dev:
    external: true
  nest2d-secret:
    external: true
