version: "3.8"

services:
  nesing-worker:
    image: nest2d-workers:local
    environment:
      - SECRET_FILE=/run/secrets/nest2d-secret-dev
      - PYTHONUNBUFFERED=1
    command: ["python", "python/worker_nest.py"]
    secrets:
      - nest2d-secret-dev
    deploy:
      update_config:
        order: start-first

  userdxf2svg-worker:
    image: nest2d-workers:local
    environment:
      - SECRET_FILE=/run/secrets/nest2d-secret-dev
      - PYTHONUNBUFFERED=1
    command: ["python", "python/worker_user_dxf_2_svg.py"]
    secrets:
      - nest2d-secret-dev
    deploy:
      update_config:
        order: start-first

secrets:
  nest2d-secret-dev:
    external: true
